Create and connect DB for users. Add profile page
justpisun/blogsite pull request #2
Opened 2021-01-05 20:36 UTC by justpisun

2021-01-05 20:53 UTC, andriiHermaniuk commented on pages/change_profile.php
> +                                    <td class="tittle">Город</td>
change "tittle"

2021-01-05 20:53 UTC, andriiHermaniuk commented on pages/submit_changes.php
> +                                    echo "<h1>Введите страну правильно</h1>";
maybe here you mean "город"?

2021-01-05 20:57 UTC, tkachuktaras commented on pages/submit_changes.php
> +                                    echo "<h1>Введите страну правильно</h1>";
yes sir

> maybe here you mean "город"?

2021-01-05 21:06 UTC, yurykozhenov requested changes

2021-01-05 21:06 UTC, yurykozhenov commented on blocks/head.php
> +<link rel="icon" href="../images/ico.png" type="image/png">
Use absolute path

2021-01-05 21:06 UTC, yurykozhenov commented on blocks/articles.php
> +        <a href="/pages/article.php?id=<?php echo $row["id"]?>" class="link__arcticle">
`link__arcticle` -> `link__article`

2021-01-05 21:06 UTC, yurykozhenov commented on blocks/head.php
> +<link rel="stylesheet" href="../css/style.css">
Use absolute path

2021-01-05 21:06 UTC, yurykozhenov commented on css/style.css
> +.backgound__opasity{
`opasity` -> `opacity`

2021-01-05 21:06 UTC, yurykozhenov commented on pages/article.php
> +    <link rel="stylesheet" href="../css/article.css">
Use absolute path

2021-01-05 21:06 UTC, yurykozhenov commented on pages/article.php
> +                        <img src="../images/user.png" class="user__img">
Use absolute path for all images

2021-01-05 21:06 UTC, yurykozhenov commented on pages/change_profile.php
> +                            <div class="tittle__profile">
`tittle__profile` -> `title__profile`

2021-01-05 21:06 UTC, yurykozhenov commented on pages/change_profile.php
> +                                    <td class="tittle">Имя и фамилия</td>
`tittle` -> `title`

2021-01-05 21:06 UTC, yurykozhenov commented on pages/login.php
> +    <link rel="stylesheet" href="../css/login_page.css">
Use absolute path

2021-01-05 21:06 UTC, yurykozhenov commented on pages/submit_changes.php
> +    }
```suggestion
    if($_COOKIE['usertime'] === NULL || $_COOKIE['usertime'] !== $user['login']) {
        header('Location: /');
        exit();
    }
```

2021-01-05 21:06 UTC, yurykozhenov commented on pages/submit_changes.php
> +    else{
Remove `else`. You do not need `else` after `exit()`

2021-01-05 21:06 UTC, yurykozhenov commented on pages/submit_changes.php
> +    mysqli_connect("localhost", "root", "", "stalker");
Remove connection, it is already created in `connect_to_db.php`

2021-01-05 21:06 UTC, yurykozhenov commented on pages/check.php
> +    else{
No need for `else` after `exit()` in `if`

2021-01-05 21:06 UTC, yurykozhenov commented on pages/check.php
> +        else{
No need for `else` after `exit()` in `if`

2021-01-05 21:06 UTC, yurykozhenov commented on pages/check.php
> +        $accept = true;
Looks like `$accept` variable is not used anywhere

2021-01-05 21:06 UTC, yurykozhenov commented on pages/auth.php
> +    else{
No need for `else` after `exit()`

2021-01-06 00:40 UTC, justpisun commented on blocks/head.php
> +<link rel="icon" href="../images/ico.png" type="image/png">
yes sir

2021-01-06 01:37 UTC, yurykozhenov approved these changes

2021-01-06 01:40 UTC, merged